export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>My First App with NextJs13</title>
      </head>
      <body>
        <nav>
          <ul>
            <li>Home</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
